added slack message if no tests

diff --git a/.github/workflows/smoke-test.yaml b/.github/workflows/smoke-test.yaml
--- a/.github/workflows/smoke-test.yaml
+++ b/.github/workflows/smoke-test.yaml
@@ -27,6 +27,41 @@ jobs:
 
             - name: check for tests
               run: test -f .github/workflows/smoke-tests/sandbox/**-test.js  ||  exit 1
+
+            - name: Notify
+              uses: homoluctus/slatify@master
+              if: github.ref == 'refs/heads/main' && failure()
+              with:
+                  type: ${{ job.status }}
+                  job_name: "*No Sandbox Tests Found*"
+                  url: ${{ secrets.SLACK_WEBHOOK }}
+                  commit: true
+                  token: ${{ secrets.GITHUB_TOKEN }}
+
+
+    staging_tests_exist:
+      # Setup
+        runs-on: ubuntu-latest
+        strategy:
+            matrix:
+                node-version: [12.x]
+        steps:
+            - name: Check out repo
+              uses: actions/checkout@v1
+              #fails if no tests present
+
+            - name: check for tests
+              run: test -f .github/workflows/smoke-tests/staging/**-test.js  ||  exit 1
+
+            - name: Notify
+              uses: homoluctus/slatify@master
+              if: github.ref == 'refs/heads/main' && failure()
+              with:
+                  type: ${{ job.status }}
+                  job_name: "*No Staging Tests Found*"
+                  url: ${{ secrets.SLACK_WEBHOOK }}
+                  commit: true
+                  token: ${{ secrets.GITHUB_TOKEN }}
       
   
     sandbox_tests:
@@ -40,17 +75,6 @@ jobs:
         steps:
             - name: Check out repo
               uses: actions/checkout@v1
-              
-            # - name: Check file existence
-            #   id: check_files
-            #   uses: andstor/file-existence-action@v1
-            #   with:
-            #     files: ".github/workflows/smoke_tests/sandbox/**-test.js"
-            #     allow_failure: true
-            # - name: File exists
-            #   if: steps.check_files.outputs.files_exists == 'true'
-            #   # Only runs if all of the files exists
-            #   run: echo All files exists!
 
             - name: Set up Node.js
               uses: actions/setup-node@v1
@@ -94,6 +118,7 @@ jobs:
     staging_tests:
         #Setup
         runs-on: ubuntu-latest
+        needs: staging_tests_exist
         strategy:
             matrix:
                 node-version: [12.x]
@@ -101,17 +126,6 @@ jobs:
         steps:
             - name: Check out repo
               uses: actions/checkout@v1
-
-            - name: Check file existence
-              id: check_files
-              uses: andstor/file-existence-action@v1
-              with:
-                files: ".github/workflows/smoke_tests/staging/**-test.js"
-                allow_failure: true
-            # - name: File exists
-            #   if: steps.check_files.outputs.files_exists == 'true'
-            #   # Only runs if all of the files exists
-            #   run: echo All files exists!
 
 
             - name: Set up Node.js
